### ISSUE TITLE
feat: Security 인증, 인가 및 JWT 설정

### ISSUE THREAD

**Issue by cjw9506** [wanted-quantum-jump/FoodieFinder#30]
## 🚀 목적 및 필요성

security 설정과 jwt 설정을 진행합니다.

## 📋 작업 상세 내용

- [x] 계정, 비밀번호로 로그인 시 JWT가 발급된다.
- [x] 이후 모든 API 요청 Header 에 JWT 가 항시 포함되며, JWT 유효성을 검증합니다.
- [x] security 설정을 진행합니다.
- [x] 로그인 API를 구현합니다.

## 📎 참고 사항

- [ ] (여기에 참고할 사항을 작성하세요.)

**Comment by O0oO0Oo** [comment]
죄송합니다. 잘못 클릭했네요
